kind: pipeline
name: pandoc-ghc

steps:
- name: aarch64-cabal-ghc865
  image: debian:buster
  privileged: true
  commands:
  - du -sh 
  - ./cabal/build.sh 19.10
  - du -sh rootfs/*
  - du -sh rootfs/var/cache/*

- name: docker-aarch64-cabal-ghc865
  image: banzaicloud/drone-kaniko
  settings:
    repo: ann17/pandoc-ghc-aarch64
    tags: cabal-ghc8.6.5
    cache: true
    username:
      from_secret: username
    password:
      from_secret: password

- name: arm-cabal-ghc865
  image: debian:buster
  privileged: true
  commands:
  - du -sh 
  - ./cabal/build.sh 19.10 arm
  - du -sh rootfs/*

- name: docker-arm-cabal-ghc865
  image: banzaicloud/drone-kaniko
  settings:
    repo: ann17/pandoc-ghc-arm
    tags: cabal-ghc8.6.5
    cache: true
    username:
      from_secret: username
    password:
      from_secret: password

- name: aarch64-cabal-ghc802
  image: debian:buster
  privileged: true
  commands:
  - du -sh 
  - ./cabal/build.sh 18.04
  - du -sh rootfs/*
  - du -sh rootfs/var/cache/*

- name: docker-aarch64-cabal-ghc802
  image: banzaicloud/drone-kaniko
  settings:
    repo: ann17/pandoc-ghc-aarch64
    tags: cabal-ghc8.0.2
    cache: true
    username:
      from_secret: username
    password:
      from_secret: password

- name: arm-cabal-ghc802
  image: debian:buster
  privileged: true
  commands:
  - du -sh 
  - ./cabal/build.sh 18.04 arm
  - du -sh rootfs/*

- name: docker-arm-cabal-ghc802
  image: banzaicloud/drone-kaniko
  settings:
    repo: ann17/pandoc-ghc-arm
    tags: cabal-ghc8.0.2
    cache: true
    username:
      from_secret: username
    password:
      from_secret: password

- name: aarch64-stack-ghc862
  image: debian:buster
  privileged: true
  commands:
  - du -sh 
  - ./stack/build.sh
  - du -sh rootfs/*
  - du -sh rootfs/var/cache/*

- name: docker-aarch64-stack-ghc862
  image: banzaicloud/drone-kaniko
  settings:
    repo: ann17/pandoc-ghc-aarch64
    tags: stack-ghc8.6.2
    cache: true
    username:
      from_secret: username
    password:
      from_secret: password

- name: arm-stack-ghc863
  image: debian:buster
  privileged: true
  commands:
  - du -sh 
  - ./stack/build.sh arm
  - du -sh rootfs/*

- name: docker-arm-stack-ghc863
  image: banzaicloud/drone-kaniko
  settings:
    repo: ann17/pandoc-ghc-arm
    tags: stack-ghc8.6.3
    cache: true
    username:
      from_secret: username
    password:
      from_secret: password
