kind: pipeline
name: pandoc-ghc

steps:
- name: ghc-aarch64-ubuntu-19-10
  image: debian:buster
  privileged: true
  commands:
  - du -sh 
  - ./ubuntu/build.sh 19.10
  - du -sh rootfs/*
  - du -sh rootfs/var/cache/*

- name: docker-ghc-aarch64-ubuntu-19-10 
  image: banzaicloud/drone-kaniko
  settings:
    repo: ann17/pandoc-ghc-aarch64
    tags: ubuntu-19.10
    cache: true
    username:
      from_secret: username
    password:
      from_secret: password

- name: ghc-arm-ubuntu-19.10
  image: debian:buster
  privileged: true
  commands:
  - du -sh 
  - ./ubuntu/build.sh 19.10 arm
  - du -sh rootfs/*

- name: docker-ghc-arm-ubuntu-19-10
  image: banzaicloud/drone-kaniko
  settings:
    repo: ann17/pandoc-ghc-arm
    tags: ubuntu-19.10
    cache: true
    username:
      from_secret: username
    password:
      from_secret: password

- name: ghc-aarch64-ubuntu-18-04
  image: debian:buster
  privileged: true
  commands:
  - du -sh 
  - ./ubuntu/build.sh 18.04
  - du -sh rootfs/*
  - du -sh rootfs/var/cache/*

- name: docker-ghc-aarch64-ubuntu-18-04
  image: banzaicloud/drone-kaniko
  settings:
    repo: ann17/pandoc-ghc-aarch64
    tags: ubuntu-18.04
    cache: true
    username:
      from_secret: username
    password:
      from_secret: password

- name: ghc-arm-ubuntu-18-04
  image: debian:buster
  privileged: true
  commands:
  - du -sh 
  - ./ubuntu/build.sh 18.04 arm
  - du -sh rootfs/*

- name: docker-ghc-arm-ubuntu-18-04
  image: banzaicloud/drone-kaniko
  settings:
    repo: ann17/pandoc-ghc-arm
    tags: ubuntu-18.04
    cache: true
    username:
      from_secret: username
    password:
      from_secret: password

- name: ghc-aarch64-alpine-3-9
  image: debian:buster
  privileged: true
  commands:
  - du -sh 
  - ./alpine-3.9/build.sh
  - du -sh rootfs/*
  - du -sh rootfs/var/cache/*

- name: docker-ghc-aarch64-alpine-3-9
  image: banzaicloud/drone-kaniko
  settings:
    repo: ann17/pandoc-ghc-aarch64
    tags: alpine-3.9
    cache: true
    username:
      from_secret: username
    password:
      from_secret: password

- name: ghc-arm-alpine-3-9
  image: debian:buster
  privileged: true
  commands:
  - du -sh 
  - ./alpine-3.9/build.sh arm
  - du -sh rootfs/*

- name: docker-ghc-arm-alpine-3-9
  image: banzaicloud/drone-kaniko
  settings:
    repo: ann17/pandoc-ghc-arm
    tags: alpine-3.9
    cache: true
    username:
      from_secret: username
    password:
      from_secret: password
