---
kind: pipeline
name: build-aarch64

steps:
- name: build-ghc-aarch64
  image: debian:buster
  privileged: true
  commands:
  - du -sh 
  - ./build.sh
  - du -sh rootfs/*

---
kind: pipeline
name: docker-aarch64
steps:
- name: docker-ghc-aarch64 
  image: banzaicloud/drone-kaniko
  settings:
    repo: ann17/pandoc-ghc-aarch64
    auto_tag: true
    username:
      from_secret: username
    password:
      from_secret: password

---
kind: pipeline
name: build-arm

steps:
- name: build-ghc-arm
  image: debian:buster
  privileged: true
  commands:
  - du -sh 
  - ./build.sh arm
  - du -sh rootfs/*

---
kind: pipeline
name: docker-arm
steps:
- name: docker-ghc-arm
  image: banzaicloud/drone-kaniko
  settings:
    repo: ann17/pandoc-ghc-arm
    auto_tag: true
    username:
      from_secret: username
    password:
      from_secret: password
